version: '3.7'

services:
  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - 80:83
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/conf.template
    environment:
      NGINX_LISTEN_PORT: 83
    depends_on:
      - api1
      - api2
    command: /bin/bash -c "envsubst '$$NGINX_LISTEN_PORT' < /etc/nginx/conf.d/conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  api1:
    build:
      context: .
    container_name: api1
    ports:
      - 81:80
    environment:
      API_NAME: app1
  api2:
    build:
      context: .
    container_name: api2
    ports:
      - 82:80
    environment:
      API_NAME: app2
